### ISSUE TITLE
Amidst does not launch on Linux Mint with java 17

### ISSUE THREAD

**Issue by TheOnlyJoeEnderman** [Treer/amidstest#37] opened 2022-11-24 00:37 UTC
The dialog box said to report the bug here. I wish I could explain more. Here is the information:

[info] Amidst for Minetest v1.4-1
[info] Current system time: 2022-11-23 18:29:28.043
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '5.4.0-132-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '17.0.1'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: '/home/joe/.minecraft'
[info] Minetest directory not found, using default mapgen v7 profile
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Found biome profile directory.
[info] Saved default biome profile "Minetest Game v5"
[info] Saved default biome profile "Minetest Game v.4"
[info] Saved default biome profile "v6"
[info] Saved default biome profile "30-biomes"
[info] Saved default biome profile "Ethereal"
[info] Saved default biome profile "Voxelgarden"
[info] Saved default biome profile "Australia v0.4"
[info] Saved default biome profile "MineClone 2"
[info] Saved default biome profile "Aotearoa (New Zealand) v0.1"
[info] Biome profile activated: Minetest Game v5
[info] Checking for additional biome profiles.
[info] Found biome profile directory.
[info] Found default biome profile "Minetest Game v5"
[info] Found default biome profile "Minetest Game v.4"
[info] Found default biome profile "v6"
[info] Found default biome profile "30-biomes"
[info] Found default biome profile "Ethereal"
[info] Found default biome profile "Voxelgarden"
[info] Found default biome profile "Australia v0.4"
[info] Found default biome profile "MineClone 2"
[info] Found default biome profile "Aotearoa (New Zealand) v0.1"
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @3bf44630
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:154)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
	at com.google.gson.Gson.getAdapter(Gson.java:407)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
	at com.google.gson.Gson.getAdapter(Gson.java:407)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
	at com.google.gson.Gson.getAdapter(Gson.java:407)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
	at com.google.gson.Gson.getAdapter(Gson.java:407)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
	at com.google.gson.Gson.getAdapter(Gson.java:407)
	at com.google.gson.Gson.fromJson(Gson.java:860)
	at com.google.gson.Gson.fromJson(Gson.java:799)
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:41)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:25)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.createFromFile(BiomeProfileDirectory.java:298)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:245)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:237)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.initParentMenu(BiomeProfileMenuFactory.java:169)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.<init>(BiomeProfileMenuFactory.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings_BiomeProfile(AmidstMenuBuilder.java:162)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings(AmidstMenuBuilder.java:129)
	at amidst.gui.main.menu.AmidstMenuBuilder.createMenuBar(AmidstMenuBuilder.java:54)
	at amidst.gui.main.menu.AmidstMenuBuilder.<init>(AmidstMenuBuilder.java:36)
	at amidst.gui.main.PerMainWindowInjector.<init>(PerMainWindowInjector.java:118)
	at amidst.PerApplicationInjector.createMainWindow(PerApplicationInjector.java:122)
	at amidst.Application.displayMainWindow(Application.java:73)
	at amidst.Application.run(Application.java:55)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:162)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by orwell96** [comment] 2023-04-10 13:07
I can confirm the issue under JDK 20 on Windows 10
```
[info] Amidst for Minetest v1.4-1
[info] Current system time: 2023-04-10 15:06:26.166
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '20'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] Minetest directory not found, using default mapgen v7 profile
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Found biome profile directory.
[info] Found default biome profile "Minetest Game v5"
[info] Found default biome profile "Minetest Game v.4"
[info] Found default biome profile "v6"
[info] Found default biome profile "30-biomes"
[info] Found default biome profile "Ethereal"
[info] Found default biome profile "Voxelgarden"
[info] Found default biome profile "Australia v0.4"
[info] Found default biome profile "MineClone 2"
[info] Found default biome profile "Aotearoa (New Zealand) v0.1"
[info] Biome profile activated: Minetest Game v5
[info] Checking for additional biome profiles.
[info] Found biome profile directory.
[info] Found default biome profile "Minetest Game v5"
[info] Found default biome profile "Minetest Game v.4"
[info] Found default biome profile "v6"
[info] Found default biome profile "30-biomes"
[info] Found default biome profile "Ethereal"
[info] Found default biome profile "Voxelgarden"
[info] Found default biome profile "Australia v0.4"
[info] Found default biome profile "MineClone 2"
[info] Found default biome profile "Aotearoa (New Zealand) v0.1"
[crash] Amidst has encounted an uncaught exception on the thread Thread[#34,AWT-EventQueue-0,6,main]
[crash] java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @2c8d66b2
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:181)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:175)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:154)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
	at com.google.gson.Gson.getAdapter(Gson.java:407)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
	at com.google.gson.Gson.getAdapter(Gson.java:407)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
	at com.google.gson.Gson.getAdapter(Gson.java:407)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
	at com.google.gson.Gson.getAdapter(Gson.java:407)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
	at com.google.gson.Gson.getAdapter(Gson.java:407)
	at com.google.gson.Gson.fromJson(Gson.java:860)
	at com.google.gson.Gson.fromJson(Gson.java:799)
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:41)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:25)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.createFromFile(BiomeProfileDirectory.java:298)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:245)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:237)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.initParentMenu(BiomeProfileMenuFactory.java:169)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.<init>(BiomeProfileMenuFactory.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings_BiomeProfile(AmidstMenuBuilder.java:162)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings(AmidstMenuBuilder.java:129)
	at amidst.gui.main.menu.AmidstMenuBuilder.createMenuBar(AmidstMenuBuilder.java:54)
	at amidst.gui.main.menu.AmidstMenuBuilder.<init>(AmidstMenuBuilder.java:36)
	at amidst.gui.main.PerMainWindowInjector.<init>(PerMainWindowInjector.java:118)
	at amidst.PerApplicationInjector.createMainWindow(PerApplicationInjector.java:122)
	at amidst.Application.displayMainWindow(Application.java:73)
	at amidst.Application.run(Application.java:55)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:162)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Treer** [comment] 2023-04-10 23:19
This looks like a duplicate of #33 
There's a workaround to it there, try

`java --add-opens java.desktop/java.awt=ALL-UNNAMED --add-opens java.desktop/java.awt.color=ALL-UNNAMED -jar amidst-minetest-v1-4-1.jar`

**Comment by Treer** [comment] 2023-04-13 15:32
could someone confirm that 1.4-2 fixes this issue 
(my own computers seem to have compatible Java SDK configurations)

* https://github.com/Treer/Amidst-for-Minetest/releases/download/v1.4-2/amidst-minetest-v1-4-2.jar
* https://github.com/Treer/Amidst-for-Minetest/releases/download/v1.4-2/amidst-minetest-v1-4-2.exe

thanks

**Comment by JoeEnderman** [comment] 2023-04-14 05:15
It works now. I had to make a script to run it, but other than that it just works. Thank you!

**Comment by Treer** [comment] 2023-04-14 05:17
Wicked, thanks for testing it and getting back to me

(I assume the script was something along the lines of `java -jar amidstest-minetest-v1-4-2.jar`)

**Comment by TheOnlyJoeEnderman** [comment] 2023-04-14 05:22
No problem, and yeah, I changed the name to just amidstest.jar, but the rest of the command eas the same. Then I put that in a text document and marked it as an executable file so I can just use that to quick launch. Linux is fun.

**Comment by JoeEnderman** [comment] 2023-04-15 18:48
You can close this if you want. Unless you think it still needs fixed.

**Closed as completed** 2023-04-16 00:54 UTC
